### ISSUE TITLE
Error in the flevels function definition in iterate-over-rows.R

### ISSUE THREAD

**Issue by aegerton** [jennybc/row-oriented-workflows#11]
With apologies, @jennybc , I think that there is an error in the flevels function definition.  

Should it not read as follows, please;-

'''
flevels <- function(df) {
  mutate(df, method = fct_reorder(method, .x = desc(time)))
}
...
There appears to be a "." missing before the "x=..."

**Comment by jennybc** [comment]
Yes, you are correct. Thanks!
