### ISSUE TITLE
Add this to row wise sum/mean examples

### ISSUE THREAD

**Issue by jennybc** [jennybc/row-oriented-workflows#8]
From @krlmlr

```
library(tidyverse)

df <- tribble(
  ~name, ~t1, ~t2, ~t3,
  "Abby", 1, 2, 3,
  "Bess", 4, 5, 6,
  "Carl", 7, 8, 9
)

df %>%
  gather("key", "value", -name) %>%
  nest(-name) %>%
  mutate(
    sum = map(data, "value") %>% map_dbl(sum),
    mean = map(data, "value") %>% map_dbl(mean)
  )
#> # A tibble: 3 x 4
#>   name  data               sum  mean
#>   <chr> <list>           <dbl> <dbl>
#> 1 Abby  <tibble [3 × 2]>     6     2
#> 2 Bess  <tibble [3 × 2]>    15     5
#> 3 Carl  <tibble [3 × 2]>    24     8
```

**Comment by krlmlr** [comment]
@hadley: Should we provide a variant of `nest()` that also gathers columns and stores them in a list of vectors (and not in a list of data frames)?

**Comment by hadley** [comment]
This will be `nest_col()` I think

**Comment by krlmlr** [comment]
On second thought, is nesting really the correct idiom here? Maybe it's more like `unite_dbl()` etc. or `unite_lst()` that would create a typed list or just a list of lists, as appropriate? `unite_lst()` would be like `select()` then `purrr::transpose()` then `mutate()`, `unite_dbl()` etc. would have the relevant data type in each list element (but requires all columns to be of the same type).
